title: Mathematical Methods
description: Course materials for the [Year/Semester] Exercise Class
remote_theme: pages-themes/minimal
google_analytics:
plugins:
  - jekyll-remote-theme

# This helps with math rendering if you use MathJax
kramdown:
  math_engine: mathjax
